# Docker compose services configuration
# Created: 2025-03-04 23:44:55
# Author: thuanpony03

version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: zalo_chatbot_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatbot_network

  mongo-express:
    image: mongo-express:latest
    container_name: zalo_chatbot_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - chatbot_network
      
  # Nếu muốn thêm Redis vào Docker Compose
  redis:
    image: redis:latest
    container_name: zalo_chatbot_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chatbot_network

networks:
  chatbot_network:
    driver: bridge

volumes:
  mongodb_data:

